name: Deploy app to gh pages
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build_react:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip-ci]')"
    runs-on: ubuntu-latest
    name: Build react
    steps:
      - uses: actions/checkout@v2
      - run : yarn install --frozen-lockfile
        shell: bash
      - run : yarn run build
        shell: bash
      - run : git config user.name github-actions
        shell: bash
      - run : git config user.email github-actions@github.com
        shell: bash
      - run : git --work-tree build add --all
        shell: bash
      - run : git commit -m "Automatic Deploy action run by github-actions"
        shell: bash
      - run : git push origin HEAD:gh-pages --force
        shell: bash
